### ISSUE TITLE
是把原midway的get等装饰器方法替换了吗？

### ISSUE THREAD

**Issue by ZQun** [MMF-FE/midway-swagger#1]
是把原midway的get等装饰器方法替换了吗？

**Comment by vfasky** [comment]
只是多包了一层，[https://github.com/MMF-FE/midway-swagger/blob/master/boilerplate/src/decorator/openApi/controller.ts#L151](https://github.com/MMF-FE/midway-swagger/blob/master/boilerplate/src/decorator/openApi/controller.ts#L151)　并没有换
